from tkinter import*
root= Tk()
root.geometry('300x400')
root.title("sign in")
name= Label(root,text="Full Name",bg='light green',font=("Arial",15)).place(x=20,y=35)
e1= Entry(root, width=40,bg="white").place(x=20,y=63,height=27)
password= Label(root,text="E-mail Address", bg='light green',font=("Arial",15)).place(x=20,y=100)
e2= Entry(root,width=40,bg="white").place(x=20,y=128,height=27)
enterpassword= Label(root,text="Enter Password", bg='light green',font=("Arial",15)).place(x=20,y=165)
e3= Entry(root,width=40,bg="white").place(x=20,y=193,height=27)
enterpassword= Label(root,text="Re-enter Password", bg='light green',font=("Arial",15)).place(x=20,y=230)
e3= Entry(root,width=40,bg="white").place(x=20,y=258,height=27)
submitButton= Button(root,text="sign in",bg="light blue",font=("Arial",15)).place(x=100,y=310)
root.config(bg="light green")
root.title("PWMS")    
root.iconbitmap('C:/Users/User/Desktop/password management system/logo.jpg')
root.mainloop()
